name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手動実行用

env:
  NEXT_PUBLIC_APP_NAME: ${{ vars.NEXT_PUBLIC_APP_NAME }}
  NEXT_PUBLIC_PAGES_PUBLISH_REPOSITORY: ${{ vars.NEXT_PUBLIC_PAGES_PUBLISH_REPOSITORY }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # mainブランチの内容をコピー
      - name: Checkout main
        uses: actions/checkout@v4

      # Issueのデータを保存してあるブランチの内容をコピー
      - name: Checkout issue data
        uses: actions/checkout@v4
        with:
          ref: data # issueが保存されているブランチ
          path: data # issueが保存されているディレクトリ
        continue-on-error: true

      # 別のホスティングサービスを使う場合
      # ここでビルドしてActionsから直接デプロイするか
      # mainとdataブランチの内容を組み合わせたものを別ブランチにpushしてデプロイをトリガーして終了する

      # Bunをインストール
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # 依存関係をインストール
      - name: Install dependencies
        run: bun install

      # 必要であればテスト等を実行

      # プロジェクトをビルド
      - name: Build
        run: bun run build

      # ビルド結果をデプロイ
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ${{ env.NEXT_PUBLIC_PAGES_PUBLISH_REPOSITORY }}
          publish_dir: out # ビルド結果が出力されたディレクトリ
